export const colors = {
    YELLO_THEME_COLOR: '#C4963D',
    YELLO_THEME_COLOR_TEXT: "#D39F3A",
    BLACK_BACKGROUND_COLOR: "#000000",
    WHITE_COLOR: "#FFFFFF",
    WHITE_COLOR_30: "#FFFFFF4D",
    WHITE_COLOR_80: "#FFFFFFCC",
    WHITE_COLOR_78: "#8E93A6C7",
    WHITE_COLOR_60: "#FFFFFF99",
    GREY_FONT_COLOR: "#D9D9D9",
    GREY_FONT_FONT_COLOR: "#8E93A6"
}