export const countryData =
    [
        { code: "AF", item: "Afghanistan", callingCode: "+93", flag: "https://flagcdn.com/w320/af.png" },
        { code: "AL", item: "Albania", callingCode: "+355", flag: "https://flagcdn.com/w320/al.png" },
        { code: "DZ", item: "Algeria", callingCode: "+213", flag: "https://flagcdn.com/w320/dz.png" },
        { code: "AD", item: "Andorra", callingCode: "+376", flag: "https://flagcdn.com/w320/ad.png" },
        { code: "AO", item: "Angola", callingCode: "+244", flag: "https://flagcdn.com/w320/ao.png" },
        { code: "AG", item: "Antigua And Barbuda", callingCode: "+1", flag: "https://flagcdn.com/w320/ag.png" },
        { code: "AR", item: "Argentina", callingCode: "+54", flag: "https://flagcdn.com/w320/ar.png" },
        { code: "AM", item: "Armenia", callingCode: "+374", flag: "https://flagcdn.com/w320/am.png" },
        { code: "AU", item: "Australia", callingCode: "+61", flag: "https://flagcdn.com/w320/au.png" },
        { code: "AT", item: "Austria", callingCode: "+43", flag: "https://flagcdn.com/w320/at.png" },
        { code: "AZ", item: "Azerbaijan", callingCode: "+994", flag: "https://flagcdn.com/w320/az.png" },
        { code: "BS", item: "Bahamas", callingCode: "+1", flag: "https://flagcdn.com/w320/bs.png" },
        { code: "BH", item: "Bahrain", callingCode: "+973", flag: "https://flagcdn.com/w320/bh.png" },
        { code: "BD", item: "Bangladesh", callingCode: "+880", flag: "https://flagcdn.com/w320/bd.png" },
        { code: "BB", item: "Barbados", callingCode: "+1", flag: "https://flagcdn.com/w320/bb.png" },
        { code: "BY", item: "Belarus", callingCode: "+375", flag: "https://flagcdn.com/w320/by.png" },
        { code: "BE", item: "Belgium", callingCode: "+32", flag: "https://flagcdn.com/w320/be.png" },
        { code: "BZ", item: "Belize", callingCode: "+501", flag: "https://flagcdn.com/w320/bz.png" },
        { code: "BJ", item: "Benin", callingCode: "+229", flag: "https://flagcdn.com/w320/bj.png" },
        { code: "BT", item: "Bhutan", callingCode: "+975", flag: "https://flagcdn.com/w320/bt.png" },
        { code: "BO", item: "Bolivia", callingCode: "+591", flag: "https://flagcdn.com/w320/bo.png" },
        { code: "BA", item: "Bosnia And Herzegovina", callingCode: "+387", flag: "https://flagcdn.com/w320/ba.png" },
        { code: "BW", item: "Botswana", callingCode: "+267", flag: "https://flagcdn.com/w320/bw.png" },
        { code: "BR", item: "Brazil", callingCode: "+55", flag: "https://flagcdn.com/w320/br.png" },
        { code: "BN", item: "Brunei", callingCode: "+673", flag: "https://flagcdn.com/w320/bn.png" },
        { code: "BG", item: "Bulgaria", callingCode: "+359", flag: "https://flagcdn.com/w320/bg.png" },
        { code: "BF", item: "Burkina Faso", callingCode: "+226", flag: "https://flagcdn.com/w320/bf.png" },
        { code: "BI", item: "Burundi", callingCode: "+257", flag: "https://flagcdn.com/w320/bi.png" },
        { code: "KH", item: "Cambodia", callingCode: "+855", flag: "https://flagcdn.com/w320/kh.png" },
        { code: "CM", item: "Cameroon", callingCode: "+237", flag: "https://flagcdn.com/w320/cm.png" },
        { code: "CA", item: "Canada", callingCode: "+1", flag: "https://flagcdn.com/w320/ca.png" },
        { code: "CV", item: "Cape Verde", callingCode: "+238", flag: "https://flagcdn.com/w320/cv.png" },
        { code: "CF", item: "Central African Republic", callingCode: "+236", flag: "https://flagcdn.com/w320/cf.png" },
        { code: "TD", item: "Chad", callingCode: "+235", flag: "https://flagcdn.com/w320/td.png" },
        { code: "CL", item: "Chile", callingCode: "+56", flag: "https://flagcdn.com/w320/cl.png" },
        { code: "CN", item: "China", callingCode: "+86", flag: "https://flagcdn.com/w320/cn.png" },
        { code: "CO", item: "Colombia", callingCode: "+57", flag: "https://flagcdn.com/w320/co.png" },
        { code: "KM", item: "Comoros", callingCode: "+269", flag: "https://flagcdn.com/w320/km.png" },
        { code: "CG", item: "Republic Of The Congo", callingCode: "+242", flag: "https://flagcdn.com/w320/cg.png" },
        { code: "CR", item: "Costa Rica", callingCode: "+506", flag: "https://flagcdn.com/w320/cr.png" },
        { code: "CI", item: "Ivory Coast", callingCode: "+225", flag: "https://flagcdn.com/w320/ci.png" },
        { code: "HR", item: "Croatia", callingCode: "+385", flag: "https://flagcdn.com/w320/hr.png" },
        { code: "CU", item: "Cuba", callingCode: "+53", flag: "https://flagcdn.com/w320/cu.png" },
        { code: "CY", item: "Cyprus", callingCode: "+357", flag: "https://flagcdn.com/w320/cy.png" },
        { code: "CZ", item: "Czech Republic", callingCode: "+420", flag: "https://flagcdn.com/w320/cz.png" },
        { code: "CD", item: "Democratic Republic Of The Congo", callingCode: "+243", flag: "https://flagcdn.com/w320/cd.png" },
        { code: "DK", item: "Denmark", callingCode: "+45", flag: "https://flagcdn.com/w320/dk.png" },
        { code: "DJ", item: "Djibouti", callingCode: "+253", flag: "https://flagcdn.com/w320/dj.png" },
        { code: "DM", item: "Dominica", callingCode: "+1", flag: "https://flagcdn.com/w320/dm.png" },
        { code: "DO", item: "Dominican Republic", callingCode: "+1", flag: "https://flagcdn.com/w320/do.png" },
        { code: "EC", item: "Ecuador", callingCode: "+593", flag: "https://flagcdn.com/w320/ec.png" },
        { code: "EG", item: "Egypt", callingCode: "	+20", flag: "https://flagcdn.com/w320/eg.png" },
        { code: "SV", item: "El Salvador", callingCode: "+503", flag: "https://flagcdn.com/w320/sv.png" },
        { code: "GQ", item: "Equatorial Guinea", callingCode: "+240", flag: "https://flagcdn.com/w320/gq.png" },
        { code: "ER", item: "Eritrea", callingCode: "+291", flag: "https://flagcdn.com/w320/er.png" },
        { code: "EE", item: "Estonia", callingCode: "+372", flag: "https://flagcdn.com/w320/ee.png" },
        { code: "SZ", item: "Eswatini", callingCode: "+268", flag: "https://flagcdn.com/w320/sz.png" },
        { code: "ET", item: "Ethiopia", callingCode: "+251", flag: "https://flagcdn.com/w320/et.png" },
        { code: "FJ", item: "Fiji", callingCode: "+679", flag: "https://flagcdn.com/w320/fj.png" },
        { code: "FI", item: "Finland", callingCode: "+358", flag: "https://flagcdn.com/w320/fi.png" },
        { code: "FR", item: "France", callingCode: "+33", flag: "https://flagcdn.com/w320/fr.png" },
        { code: "GA", item: "Gabon", callingCode: "	+241", flag: "https://flagcdn.com/w320/ga.png" },
        { code: "GM", item: "Gambia", callingCode: "+220", flag: "https://flagcdn.com/w320/gm.png" },
        { code: "GE", item: "Georgia", callingCode: "+995", flag: "https://flagcdn.com/w320/ge.png" },
        { code: "DE", item: "Germany", callingCode: "+49", flag: "https://flagcdn.com/w320/de.png" },
        { code: "GH", item: "Ghana", callingCode: "+233", flag: "https://flagcdn.com/w320/gh.png" },
        { code: "GR", item: "Greece", callingCode: "+30", flag: "https://flagcdn.com/w320/gr.png" },
        { code: "GD", item: "Grenada", callingCode: "+1", flag: "https://flagcdn.com/w320/gd.png" },
        { code: "GT", item: "Guatemala", callingCode: "+502", flag: "https://flagcdn.com/w320/gt.png" },
        { code: "GN", item: "Guinea", callingCode: "+224", flag: "https://flagcdn.com/w320/gn.png" },
        { code: "GW", item: "Guinea-Bissau", callingCode: "+245", flag: "https://flagcdn.com/w320/gw.png" },
        { code: "GY", item: "Guyana", callingCode: "+592", flag: "https://flagcdn.com/w320/gy.png" },
        { code: "HT", item: "Haiti", callingCode: "+509", flag: "https://flagcdn.com/w320/ht.png" },
        { code: "HN", item: "Honduras", callingCode: "+504", flag: "https://flagcdn.com/w320/hn.png" },
        { code: "HU", item: "Hungary", callingCode: "+36", flag: "https://flagcdn.com/w320/hu.png" },
        { code: "IS", item: "Iceland", callingCode: "+354", flag: "https://flagcdn.com/w320/is.png" },
        { code: "IN", item: "India", callingCode: "+91", flag: "https://flagcdn.com/w320/in.png" },
        { code: "ID", item: "Indonesia", callingCode: "+62", flag: "https://flagcdn.com/w320/id.png" },
        { code: "IR", item: "Iran", callingCode: "+98", flag: "https://flagcdn.com/w320/ir.png" },
        { code: "IQ", item: "Iraq", callingCode: "+964", flag: "https://flagcdn.com/w320/iq.png" },
        { code: "IE", item: "Ireland", callingCode: "+353", flag: "https://flagcdn.com/w320/ie.png" },
        { code: "IL", item: "Israel", callingCode: "+972", flag: "https://flagcdn.com/w320/il.png" },
        { code: "IT", item: "Italy", callingCode: "+39", flag: "https://flagcdn.com/w320/it.png" },
        { code: "JM", item: "Jamaica", callingCode: "+1", flag: "https://flagcdn.com/w320/jm.png" },
        { code: "JP", item: "Japan", callingCode: "	+81", flag: "https://flagcdn.com/w320/jp.png" },
        { code: "JO", item: "Jordan", callingCode: "+962", flag: "https://flagcdn.com/w320/jo.png" },
        { code: "KZ", item: "Kazakhstan", callingCode: "+7", flag: "https://flagcdn.com/w320/kz.png" },
        { code: "KE", item: "Kenya", callingCode: "+254", flag: "https://flagcdn.com/w320/ke.png" },
        { code: "KI", item: "Kiribati", callingCode: "+686", flag: "https://flagcdn.com/w320/ki.png" },
        { code: "KW", item: "Kuwait", callingCode: "+965", flag: "https://flagcdn.com/w320/kw.png" },
        { code: "KG", item: "Kyrgyzstan", callingCode: "+996", flag: "https://flagcdn.com/w320/kg.png" },
        { code: "LA", item: "Laos", callingCode: "+856", flag: "https://flagcdn.com/w320/la.png" },
        { code: "LV", item: "Latvia", callingCode: "+371", flag: "https://flagcdn.com/w320/lv.png" },
        { code: "LB", item: "Lebanon", callingCode: "+961", flag: "https://flagcdn.com/w320/lb.png" },
        { code: "LS", item: "Lesotho", callingCode: "+266", flag: "https://flagcdn.com/w320/ls.png" },
        { code: "LR", item: "Liberia", callingCode: "+231", flag: "https://flagcdn.com/w320/lr.png" },
        { code: "LY", item: "Libya", callingCode: "+218", flag: "https://flagcdn.com/w320/ly.png" },
        { code: "LI", item: "Liechtenstein", callingCode: "+423", flag: "https://flagcdn.com/w320/li.png" },
        { code: "LT", item: "Lithuania", callingCode: "+370", flag: "https://flagcdn.com/w320/lt.png" },
        { code: "LU", item: "Luxembourg", callingCode: "+352", flag: "https://flagcdn.com/w320/lu.png" },
        { code: "MK", item: "Macedonia", callingCode: "+389", flag: "https://flagcdn.com/w320/mk.png" },
        { code: "MG", item: "Madagascar", callingCode: "+261", flag: "https://flagcdn.com/w320/mg.png" },
        { code: "MW", item: "Malawi", callingCode: "+265", flag: "https://flagcdn.com/w320/mw.png" },
        { code: "MY", item: "Malaysia", callingCode: "+60", flag: "https://flagcdn.com/w320/my.png" },
        { code: "MV", item: "Maldives", callingCode: "+960", flag: "https://flagcdn.com/w320/mv.png" },
        { code: "ML", item: "Mali", callingCode: "+223", flag: "https://flagcdn.com/w320/ml.png" },
        { code: "MT", item: "Malta", callingCode: "+356", flag: "https://flagcdn.com/w320/mt.png" },
        { code: "MH", item: "Marshall Islands", callingCode: "+692", flag: "https://flagcdn.com/w320/mh.png" },
        { code: "MR", item: "Mauritania", callingCode: "+222", flag: "https://flagcdn.com/w320/mr.png" },
        { code: "MU", item: "Mauritius", callingCode: "+230", flag: "https://flagcdn.com/w320/mu.png" },
        { code: "MX", item: "Mexico", callingCode: "+52", flag: "https://flagcdn.com/w320/mx.png" },
        { code: "FM", item: "Micronesia", callingCode: "	+691", flag: "https://flagcdn.com/w320/fm.png" },
        { code: "MD", item: "Moldova", callingCode: "+373", flag: "https://flagcdn.com/w320/md.png" },
        { code: "MC", item: "Monaco", callingCode: "+377", flag: "https://flagcdn.com/w320/mc.png" },
        { code: "MN", item: "Mongolia", callingCode: "+976", flag: "https://flagcdn.com/w320/mn.png" },
        { code: "ME", item: "Montenegro", callingCode: "+382", flag: "https://flagcdn.com/w320/me.png" },
        { code: "MA", item: "Morocco", callingCode: "+212", flag: "https://flagcdn.com/w320/ma.png" },
        { code: "MZ", item: "Mozambique", callingCode: "+258", flag: "https://flagcdn.com/w320/mz.png" },
        { code: "MM", item: "Myanmar", callingCode: "+95", flag: "https://flagcdn.com/w320/mm.png" },
        { code: "NA", item: "Namibia", callingCode: "+264", flag: "https://flagcdn.com/w320/na.png" },
        { code: "NR", item: "Nauru", callingCode: "	+674", flag: "https://flagcdn.com/w320/nr.png" },
        { code: "NP", item: "Nepal", callingCode: "	+977", flag: "https://flagcdn.com/w320/np.png" },
        { code: "NL", item: "Netherlands", callingCode: "+31", flag: "https://flagcdn.com/w320/nl.png" },
        { code: "NZ", item: "New Zealand", callingCode: "+64", flag: "https://flagcdn.com/w320/nz.png" },
        { code: "NI", item: "Nicaragua", callingCode: "+505", flag: "https://flagcdn.com/w320/ni.png" },
        { code: "NE", item: "Niger", callingCode: "+227", flag: "https://flagcdn.com/w320/ne.png" },
        { code: "NG", item: "Nigeria", callingCode: "+234", flag: "https://flagcdn.com/w320/ng.png" },
        { code: "KP", item: "North Korea", callingCode: "+850", flag: "https://flagcdn.com/w320/kp.png" },
        { code: "NO", item: "Norway", callingCode: "+47", flag: "https://flagcdn.com/w320/no.png" },
        { code: "OM", item: "Oman", callingCode: "+968", flag: "https://flagcdn.com/w320/om.png" },
        { code: "PK", item: "Pakistan", callingCode: "+92", flag: "https://flagcdn.com/w320/pk.png" },
        { code: "PW", item: "Palau", callingCode: "+680", flag: "https://flagcdn.com/w320/pw.png" },
        { code: "PA", item: "Panama", callingCode: "+507", flag: "https://flagcdn.com/w320/pa.png" },
        { code: "PG", item: "Papua New Guinea", callingCode: "+675", flag: "https://flagcdn.com/w320/pg.png" },
        { code: "PY", item: "Paraguay", callingCode: "+595", flag: "https://flagcdn.com/w320/py.png" },
        { code: "PE", item: "Peru", callingCode: "+51", flag: "https://flagcdn.com/w320/pe.png" },
        { code: "PH", item: "Philippines", callingCode: "+63", flag: "https://flagcdn.com/w320/ph.png" },
        { code: "PL", item: "Poland", callingCode: "	+48", flag: "https://flagcdn.com/w320/pl.png" },
        { code: "PT", item: "Portugal", callingCode: "+351", flag: "https://flagcdn.com/w320/pt.png" },
        { code: "QA", item: "Qatar", callingCode: "+974", flag: "https://flagcdn.com/w320/qa.png" },
        { code: "RO", item: "Romania", callingCode: "+40", flag: "https://flagcdn.com/w320/ro.png" },
        { code: "RU", item: "Russia", callingCode: "+7", flag: "https://flagcdn.com/w320/ru.png" },
        { code: "RW", item: "Rwanda", callingCode: "+250", flag: "https://flagcdn.com/w320/rw.png" },
        { code: "KN", item: "Saint Kitts And Nevis", callingCode: "+1", flag: "https://flagcdn.com/w320/kn.png" },
        { code: "LC", item: "Saint Lucia", callingCode: "+1", flag: "https://flagcdn.com/w320/lc.png" },
        { code: "WS", item: "Samoa", callingCode: "+685", flag: "https://flagcdn.com/w320/ws.png" },
        { code: "SM", item: "San Marino", callingCode: "+378", flag: "https://flagcdn.com/w320/sm.png" },
        { code: "ST", item: "Sao Tome And Principe", callingCode: "	+239", flag: "https://flagcdn.com/w320/st.png" },
        { code: "SA", item: "Saudi Arabia", callingCode: "+966", flag: "https://flagcdn.com/w320/sa.png" },
        { code: "SN", item: "Senegal", callingCode: "+221", flag: "https://flagcdn.com/w320/sn.png" },
        { code: "RS", item: "Serbia", callingCode: "+381", flag: "https://flagcdn.com/w320/rs.png" },
        { code: "SC", item: "Seychelles", callingCode: "+248", flag: "https://flagcdn.com/w320/sc.png" },
        { code: "SL", item: "Sierra Leone", callingCode: "+232", flag: "https://flagcdn.com/w320/sl.png" },
        { code: "SG", item: "Singapore", callingCode: "+65", flag: "https://flagcdn.com/w320/sg.png" },
        { code: "SK", item: "Slovakia", callingCode: "+421", flag: "https://flagcdn.com/w320/sk.png" },
        { code: "SI", item: "Slovenia", callingCode: "+386", flag: "https://flagcdn.com/w320/si.png" },
        { code: "SB", item: "Solomon Islands", callingCode: "+677", flag: "https://flagcdn.com/w320/sb.png" },
        { code: "SO", item: "Somalia", callingCode: "+252", flag: "https://flagcdn.com/w320/so.png" },
        { code: "ZA", item: "South Africa", callingCode: "+27", flag: "https://flagcdn.com/w320/za.png" },
        { code: "KR", item: "South Korea", callingCode: "+82", flag: "https://flagcdn.com/w320/kr.png" },
        { code: "SS", item: "South Sudan", callingCode: "+", flag: "https://flagcdn.com/w320/ss.png" },
        { code: "ES", item: "Spain", callingCode: "+34", flag: "https://flagcdn.com/w320/es.png" },
        { code: "LK", item: "Sri Lanka", callingCode: "+94", flag: "https://flagcdn.com/w320/lk.png" },
        { code: "VC", item: "Saint Vincent And The Grenadines", callingCode: "+1", flag: "https://flagcdn.com/w320/vc.png" },
        { code: "SD", item: "Sudan", callingCode: "+249", flag: "https://flagcdn.com/w320/sd.png" },
        { code: "SR", item: "Suriname", callingCode: "+597", flag: "https://flagcdn.com/w320/sr.png" },
        { code: "SE", item: "Sweden", callingCode: "	+46", flag: "https://flagcdn.com/w320/se.png" },
        { code: "CH", item: "Switzerland", callingCode: "+41", flag: "https://flagcdn.com/w320/ch.png" },
        { code: "SY", item: "Syria", callingCode: "+963", flag: "https://flagcdn.com/w320/sy.png" },
        { code: "TJ", item: "Tajikistan", callingCode: "+992", flag: "https://flagcdn.com/w320/tj.png" },
        { code: "TZ", item: "Tanzania", callingCode: "+255", flag: "https://flagcdn.com/w320/tz.png" },
        { code: "TH", item: "Thailand", callingCode: "+992", flag: "https://flagcdn.com/w320/th.png" },
        { code: "TL", item: "East Timor", callingCode: "+992", flag: "https://flagcdn.com/w320/tl.png" },
        { code: "TG", item: "Togo", callingCode: "+992", flag: "https://flagcdn.com/w320/tg.png" },
        { code: "TO", item: "Tonga", callingCode: "+992", flag: "https://flagcdn.com/w320/to.png" },
        { code: "TT", item: "Trinidad And Tobago", callingCode: "+1", flag: "https://flagcdn.com/w320/tt.png" },
        { code: "TN", item: "Tunisia", callingCode: "+216", flag: "https://flagcdn.com/w320/tn.png" },
        { code: "TR", item: "Turkey", callingCode: "+90", flag: "https://flagcdn.com/w320/tr.png" },
        { code: "TM", item: "Turkmenistan", callingCode: "+993", flag: "https://flagcdn.com/w320/tm.png" },
        { code: "TV", item: "Tuvalu", callingCode: "+688", flag: "https://flagcdn.com/w320/tv.png" },
        { code: "UG", item: "Uganda", callingCode: "+256", flag: "https://flagcdn.com/w320/ug.png" },
        { code: "UA", item: "Ukraine", callingCode: "+380", flag: "https://flagcdn.com/w320/ua.png" },
        { code: "AE", item: "United Arab Emirates", callingCode: "+971", flag: "https://flagcdn.com/w320/ae.png" },
        { code: "GB", item: "United Kingdom", callingCode: "+44", flag: "https://flagcdn.com/w320/gb.png" },
        { code: "US", item: "United States", callingCode: "+1", flag: "https://flagcdn.com/w320/us.png" },
        { code: "UY", item: "Uruguay", callingCode: "+598", flag: "https://flagcdn.com/w320/uy.png" },
        { code: "UZ", item: "Uzbekistan", callingCode: "+998", flag: "https://flagcdn.com/w320/uz.png" },
        { code: "VU", item: "Vanuatu", callingCode: "+678", flag: "https://flagcdn.com/w320/vu.png" },
        { code: "VE", item: "Venezuela", callingCode: "+58", flag: "https://flagcdn.com/w320/ve.png" },
        { code: "VN", item: "Vietnam", callingCode: "+84", flag: "https://flagcdn.com/w320/vn.png" },
        { code: "YE", item: "Yemen", callingCode: "+967", flag: "https://flagcdn.com/w320/ye.png" },
        { code: "ZM", item: "Zambia", callingCode: "+260", flag: "https://flagcdn.com/w320/zm.png" },
        { code: "ZW", item: "Zimbabwe", callingCode: "+263", flag: "https://flagcdn.com/w320/zw.png" },
    ]

export const EventSuggestedData =
    [
        { id: 0, name: "Birthday", color: "#4161AB" },
        { id: 1, name: "Anniversarys", color: "#00A893" },
        { id: 2, name: "Music", color: "#7A5DB8" },
        { id: 3, name: "Sport's", color: "#AD4256" },
    ]

